name: Build Firmware

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          mv bin/arduino-cli /usr/local/bin/

      - name: Set up Arduino CLI
        run: |
          arduino-cli config init
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Compile the sketch
        run: |
          arduino-cli compile --fqbn esp32:esp32:m5stack-cardputer .

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: cardputer-firmware
          path: ./build/esp32*/CardputerProject.ino.bin
