name: Build and Commit Cardputer Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: latest

      - name: Install M5Stack platform
        run: |
          arduino-cli core update-index --additional-urls https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/arduino/package_m5stack_index.json
          arduino-cli core install m5stack:esp32 --additional-urls https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/arduino/package_m5stack_index.json

      - name: Install M5Cardputer library
        run: arduino-cli lib install M5Cardputer

      - name: Compile firmware
        run: arduino-cli compile --fqbn m5stack:esp32:m5stack_cardputer ./CardputerFirmware --output-dir ./firmware

      - name: Commit .bin file back to repo
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add firmware/*.bin
          git commit -m "Auto-build: add compiled .bin firmware [skip ci]" || echo "No changes to commit"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main