name: Build Cardputer Sketch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: 0.35.2

      - name: Install ESP32 board
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Build the sketch
        run: |
          arduino-cli compile --fqbn esp32:esp32:m5stack_cardputer ./CardputerTool

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: cardputer-firmware
          path: ./CardputerTool/build/esp32.*/CardputerTool.ino.bin
