name: Build Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/local/bin/

      - name: Add M5Stack Core
        run: |
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/arduino/package_m5stack_index.json
          arduino-cli core update-index
          arduino-cli core install m5stack:esp32

      - name: Install Libraries
        run: |
          arduino-cli lib install M5Cardputer
          arduino-cli lib install M5GFX
          arduino-cli lib install SD

      - name: Compile Sketch
        run: |
          mkdir -p firmware
          arduino-cli compile --fqbn m5stack:esp32:m5stack_cardputer ./shooting_tool --output-dir ./firmware

      - name: Upload firmware binary
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: firmware/shooting_tool.ino.bin